name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI
on:
  release:
    types:
      - published
      - created
      - edited
jobs:
  build-package-n-pypi-push:
    name: Build and publish Python to pypi
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
        name: Checkout Main
      - uses: actions/setup-python@v1
        name: Setup Python 3.8
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install twine
          pip install wheel
      - name: Make Wheel
        run: python setup.py sdist bdist_wheel
      - name: Push to Test PyPi
        run: twine upload --username contact@rivery.io --password ${{ secrets.PYPI_TEST_API_TOKEN }} dist/*
