on:
  push:
    # When pushing new tags with 'v...', create release
    tags:
      - 'v*'

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.merged == 'true'
        name: Make release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: false
          draft: false