name: Run Tests
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
jobs:
  run-unitests:
    name: Run Unitests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v1
        name: Setup Python 3.8
        with:
          python-version: 3.8
      - name: Run Unitests
        run: python -m unitests tests
